import { E_FUNNEL_STATUS } from '../interfaces/funnel';
import type { IFunnel } from '../interfaces/funnel';

export enum E_SUBSCRIPTION {
    WEEKLY = 'weekly',
    MONTHLY = 'monthly',
    QUARTERLY = 'quarterly',
}

export enum E_ROUTE {
    MAIN = '/',
    GENERAL = 'general',
    THEME = 'theme',
    HOME = 'home',
    QUIZ = 'quiz',
    EMAIL = 'email',
    PAYMENT = 'payment',
    ANALYTICS = 'analytics',
    UPSALE = 'upsale',
}

export const Funnels: IFunnel[] = [
    {
        id: 0,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 1,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.INACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.INACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.INACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.INACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 8,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.INACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 9,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 10,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.INACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 11,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 12,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 13,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 14,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 15,
        name: 'Website',
        website: '0.843/fxks/382,3.2.87f',
        status: E_FUNNEL_STATUS.ACTIVE,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
